repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: detect-private-key

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: []
        files: .

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    -   id: codespell # See setup.cfg for args
        args: [--skip=*.yaml]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: []

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: []
        files: .

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
        -   id: mypy
            args: [polygone_nms]
            pass_filenames: false

-   repo: local
    hooks:
        - id: check-version-changed
          name: Check VERSION changed
          entry: python scripts/check_version.py
          language: script
          files: VERSION
