name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code 📂
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build and Check Package 📦
      uses: hynek/build-and-inspect-python-package@v1.5

    - name: Download Package 📥
      uses: actions/download-artifact@v3
      with:
        name: Packages
        path: dist

    # - name: Publish package 📦 to TestPyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    #     repository-url: https://test.pypi.org/legacy/

    - name: Publish package 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
